# Generated by Django 3.2.15 on 2022-09-05 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_1', models.BooleanField(default=False)),
                ('note_2', models.BooleanField(default=False)),
                ('note_3', models.BooleanField(default=False)),
                ('note_4', models.BooleanField(default=False)),
                ('note_5', models.BooleanField(default=False)),
                ('note_6', models.BooleanField(default=False)),
                ('note_7', models.BooleanField(default=False)),
                ('note_8', models.BooleanField(default=False)),
                ('note_9', models.BooleanField(default=False)),
                ('note_10', models.BooleanField(default=False)),
                ('note_11', models.BooleanField(default=False)),
                ('note_12', models.BooleanField(default=False)),
                ('note_13', models.BooleanField(default=False)),
                ('note_14', models.BooleanField(default=False)),
                ('note_15', models.BooleanField(default=False)),
                ('note_16', models.BooleanField(default=False)),
                ('note_17', models.BooleanField(default=False)),
                ('note_18', models.BooleanField(default=False)),
                ('note_19', models.BooleanField(default=False)),
                ('note_20', models.BooleanField(default=False)),
                ('note_21', models.BooleanField(default=False)),
                ('note_22', models.BooleanField(default=False)),
                ('note_23', models.BooleanField(default=False)),
                ('note_24', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Project', max_length=64)),
                ('length', models.IntegerField(default=16)),
                ('collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_collaborator', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TuneRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tune_maker.notes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tune_maker.project')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tune_maker.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
